const artworksData = [
  // --- RENAISSANCE (6) ---
  { id: "mona-lisa", title: "Mona Lisa", artist: "Leonardo da Vinci", year: "1503", movement: "renaissance", medium: "Oil on poplar panel", dimensions: "77 cm × 53 cm", location: "Musée du Louvre, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/687px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg", description: "The portrait of Lisa Gherardini, famously known as the Mona Lisa, is a masterpiece of the Italian Renaissance. Her enigmatic expression and masterful sfumato have made it world-famous." },
  { id: "birth-venus", title: "The Birth of Venus", artist: "Sandro Botticelli", year: "1486", movement: "renaissance", medium: "Tempera on canvas", dimensions: "172.5 cm × 278.5 cm", location: "Uffizi Gallery, Florence", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg/1280px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project.jpg", description: "Depicting the goddess Venus emerging from the sea as a fully grown woman, this piece is one of the most iconic images of Western art and Neoplatonic mythology." },
  { id: "creation-adam", title: "The Creation of Adam", artist: "Michelangelo", year: "1512", movement: "renaissance", medium: "Fresco", dimensions: "280 cm × 570 cm", location: "Sistine Chapel, Vatican City", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg/1280px-Michelangelo_-_Creation_of_Adam_%28cropped%29.jpg", description: "A cornerstone of High Renaissance art, forming part of the Sistine Chapel's ceiling. It illustrates the Biblical creation narrative where God gives life to Adam." },
  { id: "school-athens", title: "The School of Athens", artist: "Raphael", year: "1511", movement: "renaissance", medium: "Fresco", dimensions: "500 cm × 770 cm", location: "Vatican Museums, Vatican City", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Raphael_School_of_Athens_Stanza_della_Segnatura_Vatican_Museums.jpg/1280px-Raphael_School_of_Athens_Stanza_della_Segnatura_Vatican_Museums.jpg", description: "Representing Philosophy, this fresco visually captures the peak of High Renaissance ideals, showcasing ancient world philosophers gathered in an idealized classical space." },
  { id: "arnolfini-portrait", title: "The Arnolfini Portrait", artist: "Jan van Eyck", year: "1434", movement: "renaissance", medium: "Oil on oak panel", dimensions: "82.2 cm × 60 cm", location: "National Gallery, London", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg/732px-Van_Eyck_-_Arnolfini_Portrait.jpg", description: "An Early Netherlandish masterpiece. Highly complex in its iconography, perspective, and use of a convex mirror to expand the scene's spatial reality." },
  { id: "last-supper", title: "The Last Supper", artist: "Leonardo da Vinci", year: "1498", movement: "renaissance", medium: "Temperamur", dimensions: "460 cm × 880 cm", location: "Santa Maria delle Grazie, Milan", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Ultima_Cena_-_Leonardo_da_Vinci_-_High_Resolution_Scale_Cropped.jpg/1280px-Ultima_Cena_-_Leonardo_da_Vinci_-_High_Resolution_Scale_Cropped.jpg", description: "One of the world's most famous paintings, capturing the dramatic moment Jesus announces that one of his disciples will betray him." },

  // --- BAROQUE (6) ---
  { id: "girl-pearl", title: "Girl with a Pearl Earring", artist: "Johannes Vermeer", year: "1665", movement: "baroque", medium: "Oil on canvas", dimensions: "44.5 cm × 39 cm", location: "Mauritshuis, The Hague", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Meisje_met_de_parel.jpg/800px-Meisje_met_de_parel.jpg", description: "A famous Dutch Golden Age 'tronie' focused on an exotic girl wearing an oversized pearl earring, highlighting Vermeer's beautiful rendering of light." },
  { id: "night-watch", title: "The Night Watch", artist: "Rembrandt van Rijn", year: "1642", movement: "baroque", medium: "Oil on canvas", dimensions: "363 cm × 437 cm", location: "Rijksmuseum, Amsterdam", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/The_Night_Watch_-_Rembrandt_van_Rijn.jpg/1280px-The_Night_Watch_-_Rembrandt_van_Rijn.jpg", description: "Famous for its colossal size, dramatic use of tenebrism (light and shadow), and the brilliant perception of motion in what would traditionally be a static military group portrait." },
  { id: "las-meninas", title: "Las Meninas", artist: "Diego Velázquez", year: "1556", movement: "baroque", medium: "Oil on canvas", dimensions: "318 cm × 276 cm", location: "Museo del Prado, Madrid", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Las_Meninas_by_Diego_Vel%C3%A1zquez_from_Prado_in_Google_Earth.jpg/1086px-Las_Meninas_by_Diego_Vel%C3%A1zquez_from_Prado_in_Google_Earth.jpg", description: "A complex composition raising questions about reality and illusion, showing the young Infanta Margaret Theresa surrounded by her entourage, with Velázquez himself painting in the background." },
  { id: "calling-matthew", title: "The Calling of St. Matthew", artist: "Caravaggio", year: "1600", movement: "baroque", medium: "Oil on canvas", dimensions: "322 cm × 340 cm", location: "San Luigi dei Francesi, Rome", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/The_Calling_of_Saint_Matthew-Caravaggio_%281599-1600%29.jpg/1280px-The_Calling_of_Saint_Matthew-Caravaggio_%281599-1600%29.jpg", description: "A definitive Baroque masterpiece, showing Caravaggio's trademark naturalism and stark chiaroscuro beam of light driving across the tax collector's dark room." },
  { id: "judith-holofernes", title: "Judith Slaying Holofernes", artist: "Artemisia Gentileschi", year: "1620", movement: "baroque", medium: "Oil on canvas", dimensions: "199 cm × 162 cm", location: "Uffizi Gallery, Florence", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Artemisia_Gentileschi_-_Judith_Slaying_Holofernes_-_WGA8563.jpg/1030px-Artemisia_Gentileschi_-_Judith_Slaying_Holofernes_-_WGA8563.jpg", description: "A powerful, visceral depiction of the biblical heroine slaying the Assyrian general, celebrated for its ruthless raw emotion and mastery of intense chiaroscuro shadows." },
  { id: "maid-of-honor", title: "The Anatomy Lesson of Dr. Nicolaes Tulp", artist: "Rembrandt van Rijn", year: "1632", movement: "baroque", medium: "Oil on canvas", dimensions: "169.5 cm × 216.5 cm", location: "Mauritshuis, The Hague", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg/1280px-Rembrandt_-_The_Anatomy_Lesson_of_Dr_Nicolaes_Tulp.jpg", description: "A dynamic group portrait of doctors surrounding a corpse, showcasing early medical science alongside Rembrandt’s evolving genius in composition." },

  // --- ROMANTICISM (6) ---
  { id: "wanderer-sea", title: "Wanderer above the Sea of Fog", artist: "Caspar David Friedrich", year: "1818", movement: "romanticism", medium: "Oil on canvas", dimensions: "94.8 cm × 74.8 cm", location: "Kunsthalle Hamburg, Germany", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg/800px-Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg", description: "The ultimate emblem of Romantic introspection. A solitary figure stands on a rocky precipice, looking out onto an expansive, mysterious sea of mountain fog." },
  { id: "liberty-people", title: "Liberty Leading the People", artist: "Eugène Delacroix", year: "1830", movement: "romanticism", medium: "Oil on canvas", dimensions: "260 cm × 325 cm", location: "Musée du Louvre, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg/1280px-Eug%C3%A8ne_Delacroix_-_La_libert%C3%A9_guidant_le_peuple.jpg", description: "Commemorating the July Revolution of 1830. An allegorical figure of Liberty leads an diverse crowd of citizens forward over barricades, waving the tricolor flag." },
  { id: "raft-medusa", title: "The Raft of the Medusa", artist: "Théodore Géricault", year: "1819", movement: "romanticism", medium: "Oil on canvas", dimensions: "491 cm × 716 cm", location: "Musée du Louvre, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_Le_Radeau_de_la_M%C3%A9duse.jpg/1280px-JEAN_LOUIS_TH%C3%89ODORE_G%C3%89RICAULT_-_Le_Radeau_de_la_M%C3%A9duse.jpg", description: "An icon of French Romanticism depicting the harrowing aftermath of a contemporary contemporary shipwreck, focusing on human despair and survival against pitiless nature." },
  { id: "third-may", title: "The Third of May 1808", artist: "Francisco Goya", year: "1814", movement: "romanticism", medium: "Oil on canvas", dimensions: "268 cm × 347 cm", location: "Museo del Prado, Madrid", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/El_tres_de_mayo_de_1808_en_Madrid.jpg/1280px-El_tres_de_mayo_de_1808_en_Madrid.jpg", description: "A groundbreaking anti-war statement depicting Spanish resistance fighters facing a faceless French Napoleonic firing squad, radiating pure terror and injustice." },
  { id: "fighting-temeraire", title: "The Fighting Temeraire", artist: "J.M.W. Turner", year: "1839", movement: "romanticism", medium: "Oil on canvas", dimensions: "90.7 cm × 121.6 cm", location: "National Gallery, London", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Turner_-_The_Fighting_Temeraire.jpg/1280px-Turner_-_The_Fighting_Temeraire.jpg", description: "A poignant, luminous tribute to the fading era of sail, showing a famous warship being towed away to be broken up by a modern industrial steam tugboat under a sunset sky." },
  { id: "saturn-son", title: "Saturn Devouring His Son", artist: "Francisco Goya", year: "1823", movement: "romanticism", medium: "Mixed media on wall", dimensions: "143.5 cm × 81.4 cm", location: "Museo del Prado, Madrid", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg/683px-Francisco_de_Goya%2C_Saturno_devorando_a_su_hijo_%281819-1823%29.jpg", description: "From Goya's terrifying 'Black Paintings' series created directly onto his villa walls, depicting the myth of the titan Cronus eating his offspring in dark madness." },

  // --- REALISM & IMPRESSIONISM (6) ---
  { id: "impression-sunrise", title: "Impression, Sunrise", artist: "Claude Monet", year: "1872", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "48 cm × 63 cm", location: "Musée Marmottan Monet, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Monet_-_Impression%2C_Sunrise.jpg/1280px-Monet_-_Impression%2C_Sunrise.jpg", description: "The painting that gave birth to the name of the Impressionist movement. A loose, mist-shrouded depiction of Le Havre harbor focusing on fleeting light and atmosphere." },
  { id: "stone-breakers", title: "The Gleaners", artist: "Jean-François Millet", year: "1557", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "83.8 cm × 111.8 cm", location: "Musée d'Orsay, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jean-Fran%C3%A7ois_Millet_-_Des_glaneuses.jpg/1280px-Jean-Fran%C3%A7ois_Millet_-_Des_glaneuses.jpg", description: "A seminal realist artwork depicting poor peasant women bending to glean stray stalks of wheat, dignifying working-class struggle without romantic exaggeration." },
  { id: "luncheon-boating", title: "Luncheon of the Boating Party", artist: "Pierre-Auguste Renoir", year: "1881", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "129.9 cm × 172.7 cm", location: "The Phillips Collection, Washington D.C.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Pierre-Auguste_Renoir_-_Le_D%C3%A9jeuner_des_canotiers.jpg/1280px-Pierre-Auguste_Renoir_-_Le_D%C3%A9jeuner_des_canotiers.jpg", description: "A peak Impressionist masterpiece capturing a sunlit, joyful social gathering of Renoir's friends relaxing on a balcony terrace along the Seine river." },
  { id: "bar-folies", title: "A Bar at the Folies-Bergère", artist: "Édouard Manet", year: "1882", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "96 cm × 130 cm", location: "Courtauld Gallery, London", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/%C3%89douard_Manet_-_A_Bar_at_the_Folies-Berg%C3%A8re_-_Google_Art_Project.jpg/1280px-%C3%89douard_Manet_-_A_Bar_at_the_Folies-Berg%C3%A8re_-_Google_Art_Project.jpg", description: "Manet's final masterpiece. A melancholic, detached barmaid looks out at the viewer while a complex mirror reflection exposes the vibrant, chaotic Paris nightlife behind her." },
  { id: "starry-rhone", title: "Starry Night Over the Rhône", artist: "Vincent van Gogh", year: "1888", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "72.5 cm × 92 cm", location: "Musée d'Orsay, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Vincent_van_Gogh_-_Starry_Night_Over_the_Rhone_-_Google_Art_Project.jpg/1280px-Vincent_van_Gogh_-_Starry_Night_Over_the_Rhone_-_Google_Art_Project.jpg", description: "A magical exploration of nighttime light, capturing the glowing gas lamps of Arles reflecting over the dark blue water under a sparkling Ursa Major constellation." },
  { id: "burial-ornans", title: "A Burial At Ornans", artist: "Gustave Courbet", year: "1850", movement: "realism-impressionism", medium: "Oil on canvas", dimensions: "315 cm × 668 cm", location: "Musée d'Orsay, Paris", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Gustave_Courbet_-_Un_enterrement_%C3%A0_Ornans -_Mus%C3%A9e_d%27Orsay.jpg/1280px-Gustave_Courbet_-_Un_enterrement_%C3%A0_Ornans_-_Mus%C3%A9e_d%27Orsay.jpg", description: "A monumentally scaled painting of an ordinary country funeral, shocking mid-century critics by treating a mundane provincial event with the grandeur traditionally reserved for history paintings." },

  // --- MODERN & SYMBOLISM (6) ---
  { id: "starry-night-main", title: "The Starry Night", artist: "Vincent van Gogh", year: "1889", movement: "modern-symbolism", medium: "Oil on canvas", dimensions: "73.7 cm × 92.1 cm", location: "Museum of Modern Art, New York", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg", description: "An iconic symbol of emotional intensity, painted from his asylum window at Saint-Rémy. The cosmic, swirling vortexes of stars reflect his inner psychological landscape." },
  { id: "the-kiss", title: "The Kiss", artist: "Gustav Klimt", year: "1908", movement: "modern-symbolism", medium: "Oil, gold, silver leaf on canvas", dimensions: "180 cm × 180 cm", location: "Belvedere Gallery, Vienna", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg/1022px-The_Kiss_-_Gustav_Klimt_-_Google_Art_Project.jpg", description: "The high point of Klimt's Golden Phase. An intimate, highly stylized embrace shrouded in shimmering, mosaic-like gilded robes influenced by Byzantine art." },
  { id: "the-scream", title: "The Scream", artist: "Edvard Munch", year: "1893", movement: "modern-symbolism", medium: "Oil, tempera, pastel on cardboard", dimensions: "91 cm × 73.5 cm", location: "National Gallery, Oslo", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery%2C_Oslo.jpg/830px-Edvard_Munch%2C_1893%2C_The_Scream%2C_oil%2C_tempera_and_pastel_on_cardboard%2C_91_x_73.5_cm%2C_National_Gallery%2C_Oslo.jpg", description: "The ultimate representation of modern existential anxiety. An agonized figure shrieks against a blood-red sky, capturing a moment of sudden sensory overload." },
  { id: "persistence-memory", title: "The Persistence of Memory", artist: "Salvador Dalí", year: "1931", movement: "modern-symbolism", medium: "Oil on canvas", dimensions: "24 cm × 33 cm", location: "Museum of Modern Art, New York", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/The_Persistence_of_Memory.jpg/800px-The_Persistence_of_Memory.jpg", description: "A legendary surrealist landscape featuring melting pocket watches draped over bizarre shapes, challenging our perception of fixed, rational time." },
  { id: "great-wave", title: "The Great Wave off Kanagawa", artist: "Katsushika Hokusai", year: "1831", movement: "modern-symbolism", medium: "Woodblock print", dimensions: "25.7 cm × 37.9 cm", location: "Metropolitan Museum of Art, New York", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Tsunami_by_Hokusai_19th_century.jpg/1280px-Tsunami_by_Hokusai_19th_century.jpg", description: "Japan's most iconic masterpiece, depicting an imposing, claw-like wave threatening fishermen boats with Mount Fuji sitting calmly in the background." },
  { id: "guernica", title: "Guernica", artist: "Pablo Picasso", year: "1937", movement: "modern-symbolism", medium: "Oil on canvas", dimensions: "349.3 cm × 776.6 cm", location: "Museo Reina Sofía, Madrid", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/PicassoGuernica.jpg/1280px-PicassoGuernica.jpg", description: "Picasso’s powerful cubist anti-war masterpiece, composed in stark monochrome to portray the sheer horror, chaos, and suffering of the aerial bombing of a Basque town." }
];

// Экспортируем данные для main.js
window.artworksData = artworksData;
